export const All_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const All_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const All_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const All_PRODUCTDETAIL_REQUEST = "ALL_PRODUCTDETAIL_REQUEST";
export const All_PRODUCTDETAIL_SUCCESS = "ALL_PRODUCTDETAIL_SUCCESS";
export const All_PRODUCTDETAIL_FAIL = "ALL_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
